name: Test Build
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.21.1
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: pnpm
      - run: pnpm install
      - run: pnpm run all
  test-global: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          root: ./example/global
      - run: cpany --version
  test-local-npm: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          root: ./example/npm
      - run: cpany --version
  test-local-yarn: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          root: ./example/yarn
      - run: cpany --version
  test-local-pnpm: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          root: ./example/pnpm
      - run: cpany --version
